export { default as DashboardLayout } from "./dashboard-layout"
export { default as DashboardBooksPage } from "./dashboard-books"
export { default as DashboardCoursesPage } from "./dashboard-courses"
export { default as DashboardHome } from "./dashboard-home"
export { default as DashboardModerationPage } from "./dashboard-moderation"
