export {default as Home } from "./home"
export {default as CoursesPage} from "./courses"
export {default as BooksPage} from "./books"
export {default as RegisterPage} from "./register"
export {default as LoginPage} from "./login"
export { default as ErrorPage } from "./error"
export { default as CustomErrorPage } from "./custom-error"
export { default as DepartmentsPage } from "./departments"
export { default as DepartmentDetailPage } from "./department-detail"
export { default as ContactPage } from "./contact"
export { default as AboutPage } from "./about"
export { default as PrivacyPage } from "./privacy"
export { default as MaterialsArchivePage } from "./materials"
export { default as RequestsPage } from "./requests"
