export {default as Book} from "./Books"
export {default as Course} from "./Courses"
export {default as  Department} from "./Departments"
export {default as User} from "./Users"
export {default as MaterialRequest} from "./MaterialRequest"
